[package]
name = "pe-fe"
version = "0.2.0"
edition = "2021"
author = "Muddanak"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"] }
sha2 = "0.10.6"
