[package]
name = "pe-fe"
version = "0.1.0"
edition = "2021"
author = "Muddanak"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
phf = { version = "0.11.1", features = ["macros"] }
